modules:
  http_2xx:
    prober: http
    timeout: 5s
    http:
      preferred_ip_protocol: ip4
      follow_redirects: true

  dns_a:
    prober: dns
    timeout: 3s
    dns:
      query_name: example.com
      query_type: A
      preferred_ip_protocol: ip4
